# include "../../jorinde.h"

# define LIB_HTTP_STRING        JORINDE_SHARED + "lib/string"
# define LIB_HTTP_ENCDEC		JORINDE_SHARED + "lib/encdec"
# define LIB_DATE		        JORINDE_SHARED + "lib/date"
# define LIB_ARRAY				JORINDE_SHARED + "lib/array"
# define ITERATOR               JORINDE_SHARED + "data/iterator"
# define BSTR                   JORINDE_SHARED + "data/bstr"
# define LIB_ITERATOR           JORINDE_SHARED + "lib/iterator"
# define LIB_XML_UTIL           JORINDE_SHARED + "lib/xmlutil"
# define LIB_EVENTS             JORINDE_SHARED + "lib/events"
# define LIB_BSTR               JORINDE_SHARED + "lib/bstr"
# define LIB_PROPERTIES			JORINDE_SHARED + "lib/properties"
